# Name of the GitHub Actions workflow
name: Playwright Github Actions

# Define when to trigger this workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run in this workflow
jobs:
  playwright-tests:
    name: Playwright shard ${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    env:
      ENV: "qa"
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node js v20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome browser for Playwright
        run: npx playwright install --with-deps chrome

      - name: Run tests for this shard
        run: npx playwright test --grep @Smoke --workers=1 --project=Chrome --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload blob report to GitHub Actions artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

  merge-reports:
    if: ${{ !cancelled() }}
    needs: [playwright-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node js v20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Download blob reports from GitHub Actions artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge blob reports into HTML report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload merged HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: playwright-report
          if-no-files-found: error
          retention-days: 14
